export interface StageDefinition {
  index: number
  key: string
  title: string
  category: 'PLANNING' | 'DATA' | 'MODELING' | 'ANALYSIS' | 'WRITING' | 'PUBLICATION'
  description: string
  deliverablePlaceholder: string
  guidelines: string[]
}

export const PAPER_TRACKER_STAGES: StageDefinition[] = [
  {
    index: 1,
    key: 'RESEARCH_IDEA_SELECTION',
    title: 'Research Idea Selection',
    category: 'PLANNING',
    description: 'Brainstorm, filter, and formulate initial high-impact scientific hypotheses and research angles.',
    deliverablePlaceholder: 'Link to idea proposal doc, brainstorming notes, or Miro board...',
    guidelines: [
      'Define problem domain and novel research angle',
      'Assess scientific impact, computational feasibility, and timeline',
      'Identify target conferences/journals for this line of work',
    ],
  },
  {
    index: 2,
    key: 'LITERATURE_REVIEW',
    title: 'Literature Review',
    category: 'PLANNING',
    description: 'Conduct exhaustive survey of related SOTA papers, taxonomy classification, and prior solutions.',
    deliverablePlaceholder: 'Link to Lit Review document, Notion/Zotero library, or survey matrix...',
    guidelines: [
      'Survey 20+ relevant benchmark papers and seminal architectures',
      'Classify works into methodological families and timelines',
      'Document weaknesses, assumptions, and failure modes of current solutions',
    ],
  },
  {
    index: 3,
    key: 'RESEARCH_GAP_IDENTIFICATION',
    title: 'Research Gap Identification',
    category: 'PLANNING',
    description: 'Pinpoint precise unsolved scientific bottlenecks, algorithmic blindspots, or evaluation deficits.',
    deliverablePlaceholder: 'Link to Research Gap formulation note or thesis prospectus chapter...',
    guidelines: [
      'Articulate why existing SOTA methods fail in specific regimes',
      'Confirm the identified gap has not been solved in recent preprints (arXiv/OpenReview)',
      'Justify mathematical or empirical novelty of addressing this gap',
    ],
  },
  {
    index: 4,
    key: 'DEFINE_OBJECTIVES_QUESTIONS',
    title: 'Define Objectives & Research Questions',
    category: 'PLANNING',
    description: 'Formalize concrete research questions (RQ1-RQ4), core hypotheses, and measurable success criteria.',
    deliverablePlaceholder: 'Link to formal Research Questions and Objectives specification...',
    guidelines: [
      'Draft 3-4 falsifiable research questions (e.g. RQ1: Does X improve sample efficiency?)',
      'Define primary and secondary evaluation metrics (e.g. F1, BLEU, latency, FLOPs)',
      'Establish minimum acceptance thresholds for positive validation',
    ],
  },
  {
    index: 5,
    key: 'METHODOLOGY_DESIGN',
    title: 'Methodology Design',
    category: 'PLANNING',
    description: 'Design the mathematical formulation, algorithmic pipeline, model architecture, and loss functions.',
    deliverablePlaceholder: 'Link to methodology design draft, architecture block diagrams, or math spec...',
    guidelines: [
      'Formalize mathematical notation, theorem sketches, and optimization objectives',
      'Design modular system pipeline from input tensor to final prediction',
      'Verify computational budget and GPU memory requirements',
    ],
  },
  {
    index: 6,
    key: 'DATASET_COLLECTION',
    title: 'Dataset Collection',
    category: 'DATA',
    description: 'Gather public benchmarks, scrape domain data, coordinate human annotations, or curate raw corpora.',
    deliverablePlaceholder: 'Link to dataset repository (Hugging Face, Kaggle, Zenodo, Drive)...',
    guidelines: [
      'Procure standard benchmark datasets or scrape raw domain archives',
      'Verify licensing, copyright, and ethical approval/consent compliance',
      'Document raw sample counts, token volumes, class distributions, and modalities',
    ],
  },
  {
    index: 7,
    key: 'DATA_CLEANING_PREPROCESSING',
    title: 'Data Cleaning & Preprocessing',
    category: 'DATA',
    description: 'Execute tokenization, normalization, deduplication, filtering, outlier removal, and train/val/test splits.',
    deliverablePlaceholder: 'Link to preprocessing script/notebook or artifact commit...',
    guidelines: [
      'Implement strict train/val/test splits (ensuring zero data leakage across groups)',
      'Clean noisy samples, corrupt tokens, and uncalibrated sensor/text anomalies',
      'Format data into standardized tensor pipelines (e.g. TFRecords, WebDataset, Hugging Face Dataset)',
    ],
  },
  {
    index: 8,
    key: 'EXPLORATORY_DATA_ANALYSIS',
    title: 'Exploratory Data Analysis (EDA)',
    category: 'DATA',
    description: 'Analyze distributions, class imbalances, sequence lengths, correlations, and dataset biases.',
    deliverablePlaceholder: 'Link to EDA Jupyter notebook, interactive dashboard, or WandB report...',
    guidelines: [
      'Generate statistical distribution plots, vocabulary histograms, and density curves',
      'Investigate label imbalance and potential demographic or domain biases',
      'Derive actionable preprocessing adjustments from EDA insights',
    ],
  },
  {
    index: 9,
    key: 'FEATURE_ENGINEERING',
    title: 'Feature Engineering',
    category: 'DATA',
    description: 'Extract handcrafted features, compute positional/spectral encodings, embeddings, or prompt templates.',
    deliverablePlaceholder: 'Link to feature pipeline module, embeddings store, or vector index...',
    guidelines: [
      'Engineer representations (e.g. geometric features, co-occurrence matrices, AST trees)',
      'Construct prompt/instruction formats or multimodal feature alignments',
      'Profile dimensionality reduction or PCA projections for signal strength',
    ],
  },
  {
    index: 10,
    key: 'MODEL_DEVELOPMENT',
    title: 'Model Development',
    category: 'MODELING',
    description: 'Implement core model architecture, custom loss layers, neural operators, and training loops in PyTorch/JAX.',
    deliverablePlaceholder: 'Link to GitHub repository, model definition code, or PR...',
    guidelines: [
      'Implement neural networks with clean modular abstraction and unit tests',
      'Integrate mixed-precision (FP16/BF16), gradient accumulation, and multi-GPU DDP/FSDP support',
      'Verify gradient flow and test on synthetic sanity-check mini-batches',
    ],
  },
  {
    index: 11,
    key: 'HYPERPARAMETER_TUNING',
    title: 'Hyperparameter Tuning',
    category: 'MODELING',
    description: 'Optimize learning rates, batch sizes, weight decays, temperature schedules, and architecture parameters.',
    deliverablePlaceholder: 'Link to Optuna/Ray Tune dashboard, WandB sweep runs, or sweep config...',
    guidelines: [
      'Perform systematic grid/Bayesian search across learning rates, schedulers, and dropout',
      'Track validation loss curves and gradient norms across iterations',
      'Document best-performing hyperparameter configurations for exact reproducibility',
    ],
  },
  {
    index: 12,
    key: 'MODEL_EVALUATION',
    title: 'Model Evaluation',
    category: 'MODELING',
    description: 'Evaluate final checkpoints on held-out test splits, benchmarks, and out-of-distribution evaluation sets.',
    deliverablePlaceholder: 'Link to evaluation logs, checkpoint evaluation tables, or metric outputs...',
    guidelines: [
      'Execute evaluation runs across all benchmark datasets with fixed random seeds',
      'Compute primary metrics (Accuracy, F1, RMSE, BLEU, mAP, Latency)',
      'Record inference speed, FLOPs count, and GPU VRAM memory footprint',
    ],
  },
  {
    index: 13,
    key: 'EXPLAINABILITY_ANALYSIS',
    title: 'Explainability & Analysis',
    category: 'ANALYSIS',
    description: 'Generate attention maps, SHAP values, feature attributions, activation probes, and failure mode analysis.',
    deliverablePlaceholder: 'Link to interpretability visualizations, attention heatmaps, or probe notebooks...',
    guidelines: [
      'Visualize attention weights, saliency maps, or latent representation clusters (t-SNE/UMAP)',
      'Conduct ablation studies isolating each individual component/loss term contribution',
      'Inspect failure modes and misclassified samples to reveal edge cases',
    ],
  },
  {
    index: 14,
    key: 'COMPARATIVE_STUDY',
    title: 'Comparative Study',
    category: 'ANALYSIS',
    description: 'Benchmark proposed approach head-to-head against all competitive SOTA baselines and prior works.',
    deliverablePlaceholder: 'Link to comparative leaderboard table, radar charts, or benchmark report...',
    guidelines: [
      'Re-run or align published baseline results under identical compute and split constraints',
      'Assemble comprehensive benchmark comparison table with bold SOTA entries',
      'Quantify relative percentage gains and trade-offs (e.g. accuracy vs efficiency)',
    ],
  },
  {
    index: 15,
    key: 'STATISTICAL_VALIDATION',
    title: 'Statistical Validation',
    category: 'ANALYSIS',
    description: 'Execute multi-seed runs, paired t-tests, Wilcoxon rank tests, and confidence interval estimation.',
    deliverablePlaceholder: 'Link to statistical validation scripts, p-value tables, and confidence intervals...',
    guidelines: [
      'Run at least 3-5 distinct random seeds for all main experiments',
      'Report mean ± standard deviation / 95% confidence intervals',
      'Compute statistical significance tests (p < 0.05, p < 0.01) against strong baselines',
    ],
  },
  {
    index: 16,
    key: 'RESULT_INTERPRETATION',
    title: 'Result Interpretation',
    category: 'ANALYSIS',
    description: 'Synthesize experimental findings into scientific takeaways, answering original research questions.',
    deliverablePlaceholder: 'Link to results summary memo, thesis results chapter, or discussion draft...',
    guidelines: [
      'Directly map findings to original Research Questions (RQ1-RQ4)',
      'Formulate clear scientific insights explaining WHY the proposed method excels',
      'Highlight real-world downstream application potential and practical utility',
    ],
  },
  {
    index: 17,
    key: 'PAPER_WRITING',
    title: 'Paper Writing',
    category: 'WRITING',
    description: 'Draft the full manuscript (Abstract, Intro, Related Work, Method, Experiments, Conclusion).',
    deliverablePlaceholder: 'Link to Overleaf project, LaTeX repository, or Google Docs manuscript...',
    guidelines: [
      'Write clear, rigorous scientific prose following conference template (IEEE/ACM/NeurIPS/CVPR)',
      'Render high-resolution vector figures (TikZ, Illustrator, draw.io) and clean LaTeX tables',
      'Ensure every equation is mathematically typed and symbols are defined in text',
    ],
  },
  {
    index: 18,
    key: 'INTERNAL_REVIEW',
    title: 'Internal Review',
    category: 'WRITING',
    description: 'Lab lead, co-authors, and student peers conduct thorough internal critique and editorial review.',
    deliverablePlaceholder: 'Link to supervisor comments, annotated PDF review, or GitHub PR review...',
    guidelines: [
      'Present draft in Lab Journal Club or weekly 1-on-1 meeting for group feedback',
      'Collect feedback on narrative flow, argument soundness, and missing baseline queries',
      'Implement revisions addressing all co-author suggestions',
    ],
  },
  {
    index: 19,
    key: 'PROOFREADING_FORMATTING',
    title: 'Proofreading & Formatting',
    category: 'WRITING',
    description: 'Perform grammar checks, page budget optimization, LaTeX compile validation, and reference sanitization.',
    deliverablePlaceholder: 'Link to formatted camera-ready compile or proofreading diff...',
    guidelines: [
      'Strictly comply with venue page limits (e.g. 8 pages + references)',
      'Sanitize bibliography BibTeX entries (ensure uniform conference titles, DOIs, arXiv links)',
      'Run language and typographic audit (eliminating widows/orphans and font warnings)',
    ],
  },
  {
    index: 20,
    key: 'PLAGIARISM_CHECK',
    title: 'Plagiarism Check',
    category: 'WRITING',
    description: 'Scan manuscript via Turnitin/iThenticate/CrossCheck for originality and citation integrity.',
    deliverablePlaceholder: 'Link to Turnitin / iThenticate similarity report (PDF or score)...',
    guidelines: [
      'Verify overall similarity score is within acceptable limits (< 10-15% excluding bibliography)',
      'Verify verbatim quotations are strictly attributed and enclosed in quotation marks',
      'Check self-plagiarism rules regarding previous workshop or thesis excerpts',
    ],
  },
  {
    index: 21,
    key: 'PAPER_SUBMISSION',
    title: 'Paper Submission',
    category: 'PUBLICATION',
    description: 'Submit paper, supplementary material, and code anonymization package to conference/journal portal.',
    deliverablePlaceholder: 'Link to OpenReview/CMT/EasyChair submission confirmation receipt...',
    guidelines: [
      'Upload anonymous manuscript and supplementary zip archive (under size limit)',
      'Fill in submission metadata (abstract, subject areas, conflict of interest, student paper tags)',
      'Store official submission confirmation number/receipt in lab records',
    ],
  },
  {
    index: 22,
    key: 'REVIEWER_RESPONSE',
    title: 'Reviewer Response',
    category: 'PUBLICATION',
    description: 'Draft rebuttals, execute requested extra experiments, and write point-by-point author response.',
    deliverablePlaceholder: 'Link to Rebuttal draft document and response to meta-reviewers...',
    guidelines: [
      'Categorize reviewer questions by theme (clarity, baselines, extra datasets, proofs)',
      'Conduct all requested ablation experiments within the rebuttal timeframe',
      'Draft respectful, structured point-by-point answers acknowledging valid critique',
    ],
  },
  {
    index: 23,
    key: 'ACCEPTANCE',
    title: 'Acceptance',
    category: 'PUBLICATION',
    description: 'Receive official acceptance notification, process camera-ready checklist, and sign copyright transfer.',
    deliverablePlaceholder: 'Link to official Acceptance email, IEEE/ACM copyright form, or camera-ready package...',
    guidelines: [
      'Celebrate acceptance with lab members and thesis advisors! 🎉',
      'Prepare camera-ready version incorporating all final reviewer recommendations',
      'Sign institutional copyright form and submit final publication source files',
    ],
  },
  {
    index: 24,
    key: 'PRESENTATION_PREPARATION',
    title: 'Presentation Preparation',
    category: 'PUBLICATION',
    description: 'Create slide deck, record virtual video presentation, and design conference poster (A0/48x36).',
    deliverablePlaceholder: 'Link to slide deck (Google Slides/Keynote/PDF) and printed poster PDF...',
    guidelines: [
      'Design slide deck focused on high-level motivation, key intuitive diagram, and punchline numbers',
      'Create A0 conference poster highlighting method, pipeline, and core result tables',
      'Conduct practice presentation rehearsals with lab supervisor for timing check (10-15 mins)',
    ],
  },
  {
    index: 25,
    key: 'PUBLICATION_DISSEMINATION',
    title: 'Publication & Dissemination',
    category: 'PUBLICATION',
    description: 'Publish open-source code, release model weights on Hugging Face, post arXiv preprint, and share on social media.',
    deliverablePlaceholder: 'Link to public GitHub release, arXiv preprint URL, Hugging Face model card, or tweet...',
    guidelines: [
      'Open-source clean, commented PyTorch/JAX code with `pip install` and `README.md` quickstart',
      'Upload model checkpoints and demo spaces on Hugging Face Hub',
      'Post non-exclusive preprint on arXiv and share announcement on Twitter/X, LinkedIn, and Lab website',
    ],
  },
]

export const CATEGORY_METADATA: Record<
  StageDefinition['category'],
  { label: string; color: string; bg: string; border: string }
> = {
  PLANNING: {
    label: 'Phase 1: Conceptualization & Design',
    color: 'text-indigo-400',
    bg: 'bg-indigo-500/10',
    border: 'border-indigo-500/30',
  },
  DATA: {
    label: 'Phase 2: Data Engineering & Analysis',
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
  },
  MODELING: {
    label: 'Phase 3: Model Architecture & Optimization',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
  },
  ANALYSIS: {
    label: 'Phase 4: Empirical Evaluation & Validation',
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/30',
  },
  WRITING: {
    label: 'Phase 5: Manuscript Preparation & Review',
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
  },
  PUBLICATION: {
    label: 'Phase 6: Submission, Rebuttal & Dissemination',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
  },
}
